# Dockerfile for the client

# Use a Python base image
FROM python:3.8-slim

RUN apt-get update && apt-get install -y alsa-utils

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the client files into the container
COPY . .

# Set the entry point to run the client
CMD ["python", "run_client.py"]
