# Dockerfile for the server

# Use a Python base image
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Upgrade pip
RUN pip install --upgrade pip --timeout 120

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the server files into the container
COPY . .

# Set the entry point to run the server
CMD ["python", "run_server.py"]
