[supervisord]
nodaemon=true

[program:tcp-server]
command=python run_server.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/tcp-server.err.log
stdout_logfile=/var/log/tcp-server.out.log

[program:ngrok]
command=ngrok tcp %(ENV_SERVER_PORT)s --log=stdout
autostart=true
autorestart=true
stderr_logfile=/var/log/ngrok.err.log
stdout_logfile=/var/log/ngrok.out.log
